const i18Obj = {
  en: {
    buttonLang: 'EN',
    promoHeading: 'Under Construction',
    promoSlogan: "We're making lots of improvements and will be back soon",
    goToEventComment: 'Check our event page when you wait:',
    eventButton: 'Go to the event',
    formErrorMessage: 'Oops... Incorrect email. Email should look like example@gmail.com',
    emailPlaceholder: 'Enter your Email and get notified',
    close: 'close',
    successMessage: 'You have successfully subscribed to the email newsletter. Hot news is already in your email',
    failedMessage: 'Sorry, something went wrong. Try again',
    success: 'success!',
    failed: 'failed...',
    buttonAccordion: 'More information',
    accordionHeader: 'All events',
    tabHeader1: 'Hawaiian party',
    tabHeader2: 'Mafia party',
    tabHeader3: 'Party on the beach',
    tabHeader4: 'Summer party',
    tabHeader5: 'Home party',
    tabHeader6: 'Party on the street',
    otherEventButton: 'Other Events',
  },

  ru: {
    buttonLang: 'RU',
    promoHeading: 'В разработке',
    promoSlogan: 'Мы делаем много улучшений и скоро вернемся',
    goToEventComment: 'Заглянить на нашу страницу событий:',
    eventButton: 'Перейти к событиям',
    formErrorMessage: 'Упс... Неверный адрес эл. почты. Эл. почта должна выглядеть как example@gmail.com',
    emailPlaceholder: 'Введите свой Email',
    close: 'закрыть',
    successMessage:
      'Вы успешно подписались на рассылку новостей по электронной почте.Горячие новости уже на вашей почте',
    failedMessage: 'Извините, что-то пошло не так. Попробуйте снова',
    success: 'успешно!',
    failed: 'ошибка...',
    buttonAccordion: 'Больше информации',
    accordionHeader: 'Все мероприятия',
    tabHeader1: 'Гавайская вечеринка',
    tabHeader2: 'Игра в мафию',
    tabHeader3: 'Вечеринка на пляже',
    tabHeader4: 'Летняя вечеринка',
    tabHeader5: 'Домашняя вечеринка',
    tabHeader6: 'Уличная вечеринка',
    otherEventButton: 'Другие События',
  },
};

export default i18Obj;
